### formations 
GET https://skillup-back.onrender.com/formations






























### formation by id
GET https://skillup-back.onrender.com/formations/1






















### search formation
GET https://skillup-back.onrender.com/formations/search?title=Reac





























### update formation
PUT http://localhost:3001/formations/1
Content-Type: application/json

{
    "title": "React creat updated",
    "description": "Learn React from scratch",
    "level": "beginner",
    "price": 199.99,
    "categorie_id": 2
}

### delete formation
DELETE http://localhost:3001/formations/1
